# Generated by Django 4.2.6 on 2023-12-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename__state_customer_state_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('ANDAMAN AND NICOBAR ISLANDS', 'PORT BLAIR'), ('ANDHRA PRADESH', 'AMARAVATI'), ('ARUNACHAL PRADESH', 'ITANAGAR'), ('ASSAM', 'DISPUR'), ('BIHAR', 'PATNA'), ('CHANDIGARH', 'CHANDIGARH'), ('CHHATTISGARH', 'RAIPUR'), ('DADRA AND NAGAR HAVELI AND DAMAN AND DIU', 'DAMAN'), ('DELHI', 'NEW DELHI'), ('GOA', 'PANAJI'), ('GUJARAT', 'GANDHINAGAR'), ('HARYANA', 'CHANDIGARH'), ('HIMACHAL PRADESH', 'SHIMLA'), ('JHARKHAND', 'RANCHI'), ('KARNATAKA', 'BANGALORE'), ('KERALA', 'THIRUVANANTHAPURAM'), ('LAKSHADWEEP', 'KAVARATTI'), ('MADHYA PRADESH', 'BHOPAL'), ('MAHARASHTRA', 'MUMBAI'), ('MANIPUR', 'IMPHAL'), ('MEGHALAYA', 'SHILLONG'), ('MIZORAM', 'AIZAWL'), ('NAGALAND', 'KOHIMA'), ('ODISHA', 'BHUBANESWAR'), ('PUDUCHERRY', 'PUDUCHERRY'), ('PUNJAB', 'CHANDIGARH'), ('RAJASTHAN', 'JAIPUR'), ('SIKKIM', 'GANGTOK'), ('TAMIL NADU', 'CHENNAI'), ('TELANGANA', 'HYDERABAD'), ('TRIPURA', 'AGARTALA'), ('UTTAR PRADESH', 'LUCKNOW'), ('UTTARAKHAND', 'DEHRADUN'), ('WEST BENGAL', 'KOLKATA')], max_length=250),
        ),
    ]
